[project]
name = "shrec2025_protein"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
dependencies = [
    "numpy>=2.2.4",
    "scikit-learn>=1.6.1",
]
